//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ziyatdinova420_Shaitanet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public int ID_feed { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID_type_feed { get; set; }
    
        public virtual Type_feed Type_feed { get; set; }
    }
}
