//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ziyatdinova420_Shaitanet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_user { get; set; }
        public string Name { get; set; }
        public Nullable<int> Login { get; set; }
        public Nullable<int> Password { get; set; }
        public Nullable<int> ID_type { get; set; }
    
        public virtual Type_user Type_user { get; set; }
    }
}
